apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pravegaOp.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "pravegaOp.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "pravegaOp.fullname" . }}
    spec:
      containers:
      - name: {{ template "pravegaOp.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: "WATCH_NAMESPACE"
          value: "{{ .Values.watch.namespace }}"
