{{if ne .Values.watch.namespace ""}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "pravegaOp.fullname" . }}
rules:
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-{{ template "pravegaOp.fullname" . }}
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ template "pravegaOp.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{end}}